const express=require('express')
const adminRoute=express()
const {handleSignIn,handleSignUp}=require('../controllers/Admin/AdminController')
const{handleLabourAdding,handleLabourDetails,handleAttendance,salarycalculationoflabour,handleLabourById,labourAttendanceById,salarycalculation}=require('../controllers/Admin/LabourController')
const{handleStaffAdding,handleStaffDetails,handleAttendanceofStaff,salarycalculationofStaff,handleStaffById}=require('../controllers/Admin/StaffController')
const{handleProjectAdding,ProjectList,ProjectListById}=require('../controllers/Admin/ProjectController')
const{handleAddContract,ContractList,ContractListById}=require('../controllers/Admin/ContractController')
const upload=require('../Middleware/Multer')
const Auth=require('../Middleware/Auth')

//The routes for admin authentication

adminRoute.post('/login',handleSignIn)
adminRoute.post('/signup',handleSignUp)
adminRoute.post('/addlabour',upload.fields([{ name: 'proof', maxCount: 1 }, { name: 'photo', maxCount: 1 }]),handleLabourAdding)
adminRoute.get('/labourslist',handleLabourDetails)
adminRoute.get('/labourbyid',handleLabourById)
adminRoute.post('/addstaff',upload.fields([{ name: 'proof', maxCount: 1 }, { name: 'photo', maxCount: 1 }]),handleStaffAdding)
adminRoute.get('/staffslist',handleStaffDetails)
adminRoute.get('/staffByid',handleStaffById)
adminRoute.post('/labourattendance',handleAttendance)
adminRoute.post('/staffattendance',handleAttendanceofStaff)
adminRoute.get('/salarycalculation',salarycalculationoflabour)
adminRoute.post('/salaryoflabour',salarycalculation)
adminRoute.get('/staffsalary',salarycalculationofStaff)
adminRoute.post('/addproject',handleProjectAdding)
adminRoute.post('/AddContract',handleAddContract)
adminRoute.get('/ContractList',ContractList)
adminRoute.get('/ContractById',ContractListById)
adminRoute.get('/projectList',ProjectList)
adminRoute.get('/projectById',ProjectListById)
adminRoute.get('/labourattendanceById',labourAttendanceById)

module.exports=adminRoute